config/routes.rb
Rails.application.routes.draw do

  resources :files, :as => :files, :only => [:index, :new, :show] do
    collection do
      get '/:filter/:page', :action => 'index'
    end
  end

  post '/file' => 'files#create'
  root :to => "files#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord

  scope :latest, ->() { order('id DESC') }

  has_one_attached :filename
  validates_presence_of :name, :tags

  before_save :sanitize_tags

  # @params <Array, include_tags> array containing the tags we're looking for
  # @params <Array, exclude_tags> array containing the tags we want to exclude
  def self.tag_filter(include_tags, exclude_tags = [])
    query = self.all
    include_tags.each do |included_tag|
      query = query.where("tags ILIKE ?", "%#{included_tag}%")
    end
    exclude_tags.each do |excluded_tag|
      query = query.where("tags NOT ILIKE ?", "%#{excluded_tag}%")
    end
    query
  end

  def self.related_content(search, include_tags, exclude_tags = [])
    related_tags = (search.flat_map(&:tag_list) - include_tags).uniq
    Hash[
      related_tags.map do |tag|
        [tag, self.tag_filter([tag], exclude_tags).count]
      end
    ]
  end

  def tag_list
    tags.to_s.split(',')
  end

  private

    def sanitize_tags
      self.tags = tags.split(',').map(&:strip).sort.join(',')
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  include ApplicationHelper

  def index
    if params[:filter].present?
      included_tags, excluded_tags = sanitize_tags(params[:filter])
      @resources = Resource.tag_filter(included_tags, excluded_tags).page(params[:page]).per(10)
      @related = Resource.related_content(@resources, included_tags, excluded_tags)
    else
      @resources = Resource.latest.page(params[:page]).per(10)
    end
  end

  def show
    @resource = Resource.find(params[:id])
  end

  def create
    user = Resource.create!(resource_params)
    redirect_to(files_path)
  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = "Invalid information: #{e.message}"
    redirect_to(files_new_path)
  end

  private
    def resource_params
      params.require(:resource).permit(:name, :tags, :filename)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_file_size(number)
    case
    when number < 1024
      "#{number} bytes"
    when number.between?(1024, 1024*1024)
      "#{(number/1024)} Kb"
    when number > 1024*1024
      "#{(number/(1024*1024))} Mb"
    else
      number
    end
  end

  def generate_tag_link(tags)
    tags.map do |tag|
      encoded_tag = URI.encode("+#{tag} ")
      "<a href=\"#{files_path}/#{encoded_tag}/1\">#{tag}</a>"
    end.join(',')
  end

  def sanitize_tags(tag_string)
    include_tags, exclude_tags = tag_string.squeeze(' ').split(' ').partition do |tag|
      tag.start_with?('+')
    end
    exclude_tags ||= [] # for the case when we don't have "negative tags"
    exclude_tags.select! { |tag| tag.start_with?('-') } # just sanitize the tag list removing those ones not including a "-"
    (exclude_tags + include_tags).map { |tag| tag.gsub!(/\W/,'') }
    [include_tags, exclude_tags]
  end

  def render_resource(file)
    case file.filename.content_type.downcase
    when "image/jpeg", "image/png"
      "<img src='#{url_for(file.filename)}' width='100%' class='rounded'/>".html_safe
    else
      "<div class='default_preview' class='rounded'><h2>Preview not available</h2><p class='text-center'>#{file.filename.content_type.downcase}</p></div>".html_safe
    end
  end
end

app/helpers/resource_helper.rb
module ResourceHelper
end

app/views/files/index.html.erb
<h1>
  File system
  <span class="badge badge-secondary"><%= @resources.size %> records</span>
</h1>

<div class="row">
  <div class="col-<%= (@related.present?) ? '9':'12'%>">
    <% if @resources.any? %>
    <table class="table table-hover table-striped">
      <tr>
        <thead>
          <th>Name</th>
          <th>Tags</th>
          <th>UUID</th>
          <th>Size</th>
          <th>Content Type</th>
        </thead>
        <tbody>
          <%- @resources.each do |resource| %>
          <tr>
            <td><a href="<%= file_path(:id => resource.id) %>"><%= resource.name %></a></td>
            <td><%= raw generate_tag_link(resource.tag_list) %></td>
            <td><%= resource.filename.filename %></td>
            <td><%= format_file_size(resource.filename.byte_size) %></td>
            <td><%= resource.filename.content_type %></td>
          </tr>
          <%- end %>
        </tbody>
      </tr>
    </table>
    <% else %>
      <p text="center">There are no files yet</p>
    <% end %>

    <%= paginate @resources %>
  </div>
  <% if @related.present? %>
    <div class="col-3">
      <div class="card">
        <h5 class="card-header">Featured</h5>
          <ul class="list-group list-group-flush">
          <% @related.each do |(tag,files_count)| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <a href="/files/+<%= tag %>/1"><%= tag %></a>
              <span class="badge badge-primary badge-pill"><%= files_count %></span>
            </li>
          <% end %>
          </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/files/new.html.erb
<div class="container">
  <h1>Upload a new file</h1>

  <hr>
  <% if flash[:error] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_for(Resource.new, {:url => "/file", :html => { :class=> "form" }}) do |form| %>
    <div class="form-group">
      <%= form.text_field :name, :class => 'form-control', :placeholder => 'Enter a name or description' %>
    </div>
    <div class="form-group">
      <%= form.text_field :tags, :class => 'form-control', :placeholder => 'Enter a tag or list of tags' %>
    </div>
    <div class="form-group custom-file">
      <%= form.file_field :filename, multiple: false, direct_upload: true, :class => 'custom-file-input' %>
      <label class="custom-file-label" for="resource_filename">Choose file</label>
    </div>
    <div class="form-group">
      <hr>
      <%= form.submit "Create", :class => 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/files/show.html.erb
<h1>
  <%= @resource.filename.filename %>
</h1>
<div class="row">
  <div class="col-8">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= @resource.filename.filename %>
          <span class="badge badge-primary badge-pill"><%= format_file_size(@resource.filename.byte_size) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <b>Name:</b> <%= @resource.name %>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <b>Tags:</b> <%= @resource.tags %>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-4">
    <%= render_resource(@resource) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Up and Running</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Up &amp; Running app</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= files_path %>">List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_file_path %>">Upload</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" action="<%= files_path %>">
            <input class="form-control mr-sm-2" type="search" name="filter" placeholder="e.g +tag1 +tag2 -tag4" aria-label="Search" value="<%= params[:filter]%>">
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    <div class="container-fluid main_container">
      <%= yield %>
    </div>
    <%= content_for(:javascript) %>
  </body>
</html>